# Generated by Django 4.0.4 on 2022-08-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('branch1', models.CharField(max_length=100)),
                ('semester1', models.CharField(max_length=100)),
                ('branch2', models.CharField(max_length=100)),
                ('semester2', models.CharField(max_length=100)),
                ('branch3', models.CharField(max_length=100)),
                ('semester3', models.CharField(max_length=100)),
                ('classroom_code1', models.CharField(max_length=100)),
                ('classroom_code2', models.CharField(max_length=100)),
                ('classroom_code3', models.CharField(max_length=100)),
                ('faculty1', models.CharField(max_length=100)),
                ('faculty2', models.CharField(max_length=100)),
                ('faculty3', models.CharField(max_length=100)),
                ('theory', models.IntegerField()),
                ('tutorial', models.IntegerField()),
                ('lab', models.IntegerField()),
                ('lab_name', models.CharField(max_length=100)),
            ],
        ),
    ]
